spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.96.74.32:3306/hssws?allowPublicKeyRetrieval=true&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: ASDzxc1993.
  jpa:
    show-sql: true
log:
  level: error
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/